# Generated by Django 2.2.5 on 2019-09-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.URLField(default=None),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.URLField(default=None),
        ),
    ]
